### ISSUE TITLE
Remove extraneous build envs

### ISSUE THREAD

**Issue by shahankhatch** [cosmos/cips#9]
There is a website build approach that doesn't match the cosmos brand nor the ghpages build approach from core repos. So I'm removing all html, css, build approaches that have come from the previous build. 

The approach from core repos should work for this repo as well, and we'll need another PR to set up this repo's ghpages generation.

**Comment by tac0turtle** [comment]
could you include a file similar to this to avoid breaking the current github pages. https://github.com/cosmos/docs/blob/main/.github/workflows/deployment.yml
